### ISSUE TITLE
Umbraco 7.7.6 not fully compatible 

### ISSUE THREAD

**Issue by samsam321** [Offroadcode/umbraco-backoffice-visualization#9]
First, thanks you for your great extension to save me much time to find the inheritance of document type.

I have installed in my application which the umbraco version is 7.7.6

when I click the link under column "Compositions/Associated DocTypes" , error prompted as below

> Server Error in '/' Application.
> 
> The resource cannot be found.
> 
> Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 
> 
> Requested URL: /umbraco/settings/editNodeTypeNew.aspx
> 
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2114.0

**Comment by cssquirrel** [comment]
@samsam321 Sorry for the slow response, as this came in just as we were getting back from holiday break. I'm looking into the issue now and I'll report back.

**Comment by cssquirrel** [comment]
I've made fixes to the links for the hyperlinks responsible for taking you to the docTypes and tested the solution in Umbraco 7.6. Looks to be acting as expected now.

**Comment by samsam321** [comment]
Thanks for fixing and working good  ^^ [thumbUp]
